# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 15:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinder', '0002_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='NA', max_length=5000),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='NA', max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookfinder.Book'),
        ),
    ]
