# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinder', '0004_auto_20161204_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default='NA'),
        ),
    ]
