# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinder', '0005_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gid',
            field=models.CharField(default='NA', max_length=200, unique=True),
        ),
    ]
